---
title: "stm.R"
author: "D. Danilenko"
date: "2023-08-16"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load necessary libraries}
# load all the necessary libraries
library("stm")
library("quanteda")
library("stminsights")
library("tidyverse")
library("readxl")
library("dplyr")
library("ggplot2")
library("tidytext")
library("gutenbergr")
library("reshape2")
library("gridExtra")
library("forestplot")
library("wesanderson")
library("tidyr")
library("betareg")
library("hrbrthemes")
library("plotly")
library("viridis")
library("heatmaply")
library("countrycode")
library("margins")
library("marginaleffects")
```

```{r load the dataset}
# load the dataset
# rm(data)
data <- read.csv('data/data_complete.csv', header = TRUE)
data <- data %>%
  select(c("id", "majority_female", "abstract","title","keywords",
           "majority_female_binary","first_author_female","last_author_female","subfield","impact","X1_gii_quartile", "X2_gii_quartile", "year"))

data$text <- "text"

# prepare the variables for stm
data <- data %>%
  mutate(impact = if_else(is.na(impact) | impact == "None", "unknown", impact))
data$subfield <- as.factor(data$subfield)
data$first_author_female <- as.factor(data$first_author_female)
data$last_author_female <- as.factor(data$last_author_female)
data$majority_female_binary <- as.factor(data$majority_female_binary)
data$impact <- as.factor(data$impact)
data$X1_gii_quartile <- as.factor(data$X1_gii_quartile)
data$X2_gii_quartile <- as.factor(data$X2_gii_quartile)
```

```{r process the data, create tokens}
### DATA PROCESSING ###
# building a corpus using quanteda
# combine title, abstract and keywords in a column called text
data$text <- paste(data$title, data$abstract, data$keywords)

# get rid of the copyright information in our corpus
data <- data %>% separate(text, c("text","copyright"), sep = "\\(c\\)\\s*\\d+", extra="merge", remove = TRUE) #removes (c) followed by numbers - this covers most copyright messages
data$text <- gsub("all rights reserved"," ",as.character(data$text))

# create the actual CORPUS 
corp <- corpus(data, text_field = "text")
summary(corp, 3)

# the function automatically assumes all other columns contain document variables
head(docvars(corp)) 

# create TOKENS from this - this basically just means cutting up the text into individual words
toks <- tokens(corp)
#the below is a fairly standard list for pre-processing
toks <- tokens(corp, remove_punct = TRUE, remove_symbols = TRUE) %>% #create tokens w/o punctuation or symbols
  tokens_tolower() %>% #lowercase -- note the pipe means this function doesn't need any input
  tokens_remove(pattern = stopwords("en"), #remove stopwords
                min_nchar = 2) %>% #remove short words. AMR is three letters, so best keep it to 2
  tokens_wordstem(language = "en") #Using snowball stemmer

# create two dfms: one with unigrams and one with bi-grams
dfm_single = dfm(toks)%>%
  dfm_trim(min_termfreq = 100, termfreq_type = "count", max_docfreq=0.95, docfreq_type = "prop")

toks_bigram <- tokens_ngrams(toks, n = 2, skip = 1:2)
dfm_bigram <- dfm(toks_bigram) %>%
  dfm_trim(min_termfreq = 100, termfreq_type = "count", max_docfreq=0.95, docfreq_type = "prop")

# combine
dfm = cbind(dfm_bigram, dfm_single)

# show most-frequent tokens:
topfeatures(dfm, 15) # should include some bi-grams now

# you need to do something with the data before quanteda
# when you define docvars
```

```{r create topic models with varying K}
### TOPIC MODELLING ###
storage <- manyTopics(dfm, seed=1608,
                      K=c(75,100,125),
                      runs = 12,
                      prevalence =~first_author_female + last_author_female + majority_female_binary + 
                        s(year) + subfield + X1_gii_quartile + X2_gii_quartile + impact,
                      data = docvars(dfm),
                      max.em.its = 100,
                      control = list(alpha = 0.5, #Lower than default of 50/k to allow documents to have more topics -> makes small topics more likely to show up
                                     eta = 0.1))  #Higher than default of 0.01 to create topics composed of more words -> more clarity for complex topics

```

```{r explore multiple models}
# get the models and save them
model1 <- storage$out[[1]]
model2 <- storage$out[[2]]
model3 <- storage$out[[3]]

saveRDS(model3, file = "170823_3.Rds")

# explore the outputs
# see the topic frequency with the top n keywords:
plot.STM(model1, type="summary", n = 5, xlim=c(0,.12))
plot.STM(model2, type="summary", n = 5, xlim=c(0,.12))
plot.STM(model3, type="summary", n = 5, xlim=c(0,.12))

# print out topics with keywords
topics <- data.frame(labelTopics(model1, c(1:model1$settings$dim$K), n=10)$prob)
topics$vocab <- "text"
topics$vocab <- paste(topics$X1,topics$X2,topics$X3,topics$X4,topics$X5,topics$X6,topics$X7, topics$X8, topics$X9, topics$X10)
topics = subset(topics, select = -c(X1, X2, X3, X4, X5, X6, X7, X8, X9, X10))

topics2 <- data.frame(labelTopics(model2, c(1:model2$settings$dim$K), n=10)$prob)
topics2$vocab <- "text"
topics2$vocab <- paste(topics2$X1,topics2$X2,topics2$X3,topics2$X4,topics2$X5,topics2$X6,topics2$X7, topics2$X8, topics2$X9, topics2$X10)
topics2 = subset(topics2, select = -c(X1, X2, X3, X4, X5, X6, X7, X8, X9, X10))

topics3 <- data.frame(labelTopics(model3, c(1:model3$settings$dim$K), n=10)$prob)
topics3$vocab <- "text"
topics3$vocab <- paste(topics3$X1,topics3$X2,topics3$X3,topics3$X4,topics3$X5,topics3$X6,topics3$X7, topics3$X8, topics3$X9, topics3$X10)
topics3 = subset(topics3, select = -c(X1, X2, X3, X4, X5, X6, X7, X8, X9, X10))

write.csv(topics,"topics1.csv")
write.csv(topics2,"topics2.csv")
write.csv(topics3,"topics3.csv")
```

```{r searchK}
set.seed(210823)
K <- c(110,120,130,140,150)
kresult <- searchK(documents = dfm, K = K,
                   N = floor(0.1 * nrow(docvars(dfm))),
                   prevalence =~first_author_female + last_author_female + majority_female_binary + 
                     s(year) + subfield + X1_gii_quartile + X2_gii_quartile + impact, data = docvars(dfm),
                   max.em.its = 20)
plot(kresult)
```

```{r selectModel}
# find a good model for K = 120
# fit another one for the same K with previously used settings - explore them quantitatively, choose the best one and label

mod.out <- selectModel(dfm, K=120, prevalence =~first_author_female + last_author_female + majority_female_binary + 
                     s(year) + subfield + X1_gii_quartile + X2_gii_quartile + impact, data = docvars(dfm), runs = 5, max.em.its = 20)
plotModels(mod.out)

model120 <- mod.out$runout[[1]]

saveRDS(model120, file = "240823_120.Rds")

plot.STM(model120, type="summary", n = 5, xlim=c(0,.12))

# get highest frequency words

topics120 <- data.frame(labelTopics(model120, c(1:model120$settings$dim$K), n=10)$prob)
topics120$vocab <- "text"
topics120$vocab <- paste(topics120$X1,topics120$X2,topics120$X3,topics120$X4,topics120$X5,topics120$X6,topics120$X7, topics120$X8, topics120$X9, topics120$X10)
topics120 = subset(topics120, select = -c(X1, X2, X3, X4, X5, X6, X7, X8, X9, X10))

write.csv(topics120,"topics120.csv")

```

```{r stm k=120}
### STM (k = 120) ###

model120_1 <- stm(dfm, seed=1608,
                      K=120,
                      prevalence =~first_author_female + last_author_female + majority_female_binary + 
                        s(year) + subfield + X1_gii_quartile + X2_gii_quartile + impact,
                      data = docvars(dfm),
                      max.em.its = 75,
                      control = list(alpha = 0.5, #Lower than default of 50/k to allow documents to have more topics -> makes small topics more likely to show up
                                     eta = 0.1))  #Higher than default of 0.01 to create topics composed of more words -> more clarity for complex topics

saveRDS(model120_1, file = "240823_120_1.Rds")

plot.STM(model120_1, type="summary", n = 5, xlim=c(0,.12))

# get highest frequency words

topics120_1 <- data.frame(labelTopics(model120_1, c(1:model120_1$settings$dim$K), n=10)$prob)
topics120_1$vocab <- "text"
topics120_1$vocab <- paste(topics120_1$X1,topics120_1$X2,topics120_1$X3,topics120_1$X4,topics120_1$X5,topics120_1$X6,topics120_1$X7, topics120_1$X8, topics120_1$X9, topics120_1$X10)
topics120_1 = subset(topics120_1, select = -c(X1, X2, X3, X4, X5, X6, X7, X8, X9, X10))

write.csv(topics120_1,"topics120_1.csv")
```

```{r explore topic model(s)}
### TOPIC MODEL EXPLORATION ###
model120_1 <- readRDS(file = "data/240823_120_1.Rds")

# get the most representative documents for each topic

thoughts120_1 <- findThoughts(model120_1, texts = data$text, n = 5, meta = docvars(dfm))
thoughts <- data.frame(thoughts120_1$docs)
write.csv(thoughts,"thoughts120_1.csv")
```

```{r define justice topics}
# define CJ topics through manual exploration

cj_topics <- c(12,21,25,37,44,50,56,80,83,91,101,118,119) 
cj_topicnames <- c("Resilience","Food Security","Vulnerability","Adaptive Capacity","Governance","Local Knowledge","Island Territories","Climate Finance","Rural Households","Transformation Discourse","Community","Social Capital","Migration")
cj_topicnames1 <- c("resilience","food_security","vulnerability","adaptive_capacity","governance","local_knowledge","island_territories","climate_finance","rural_households","transformation_discourse","community","social_capital","migration")

```

```{r estimate metadata effects}
set.seed(2911)

# try fewer degrees of freedom for the spline, try taking out the spline
prep1 <-  estimateEffect(~first_author_female, #+ s(year) + 
                           #subfield +
                           #X1_gii_quartile + 
                         #impact + 
                          # subfield*first_author_female +
                           #impact*first_author_female +
                           #X1_gii_quartile*first_author_female,
                         model120_1,
                         metadata = dfm_stm$meta)
summary(prep1)

# try to change the encoding of data for the gender variable
# so we want to get a separate estimate for 0.0, 1.0, and unknown

prep2 <-  estimateEffect(~last_author_female +
                           s(year) + subfield + X2_gii_quartile + impact + 
                           subfield*last_author_female +
                           impact*last_author_female +
                           X2_gii_quartile*last_author_female, 
                         model120_1,
                         metadata = docvars(dfm))

summary(prep2)

prep3 <-  estimateEffect (~majority_female_binary +
                           s(year) + subfield + X2_gii_quartile + impact + 
                           subfield*majority_female_binary +
                           impact*majority_female_binary +
                           X2_gii_quartile*majority_female_binary, 
                          model120_1,
                         metadata = docvars(dfm))
summary(prep3)
```

```{r stm_insights}
# STM insights web version
out <- quanteda::convert(dfm, to = "stm",docvars=docvars(dfm))
save.image("291123_stm.RData") # this has to contain prep
run_stminsights()
```

```{r quanteda metadata conversion}
#STM can take Quanteda dfms directly, so there is usually no reason to convert
#However, sometimes STM gets confused about data types etc. If you want to convert, use the below
#Note that in the stm call, you then need to manually input the docs, vocab and meta data
#Also the docvars bit is absolutely essential for STM's co-variance to work!
dfm_stm <- quanteda::convert(dfm, to = c("stm"),docvars=docvars(dfm))
dfm_stm$meta$year <- as.numeric(dfm_stm$meta$year)
dfm_stm$meta$first_author_female <- as.factor(dfm_stm$meta$first_author_female)
dfm_stm$meta$last_author_female <- as.factor(dfm_stm$meta$last_author_female)
dfm_stm$meta$majority_female_binary <- as.factor(dfm_stm$meta$majority_female_binary)
docs <- dfm_stm$documents
vocab <- dfm_stm$vocab
meta <- dfm_stm$meta
```

```{r extract mean topic score}
# extract mean topic prevalence

proportions_table <- make.dt(model120_1)
mean_proportions <- as.data.frame(summarize_all(proportions_table, mean))
mean_proportions <- subset(mean_proportions, select = -docnum)
new_col_names <- as.character(1:120)
colnames(mean_proportions) <- new_col_names

# make graphs with the relative change instead of absolute

mean_proportions_f <- mean_proportions %>%
  select(all_of(cj_topics))

transformed_df <- mean_proportions %>%
  pivot_longer(everything(), names_to = "topic", values_to = "mean_proportion")

transformed_df_f <- transformed_df %>%
  filter(topic %in% cj_topics)
```

```{r extract effect as difference}
### EXTRACT AND EXPLORE EFFECTS ### 
### GENDER ###

effects1 <- get_effects(estimates = prep1,
                       variable = 'first_author_female',
                       type = 'difference',
                       cov_val1="1.0",cov_val2="0.0")

effects1_f <- effects1 %>%
  filter(topic %in% cj_topics)

effects2 <- get_effects(estimates = prep2,
                        variable = 'last_author_female',
                        type = 'difference',
                        cov_val1="1.0",cov_val2="0.0")

effects3 <- get_effects(estimates = prep3,
                        variable = 'majority_female_binary',
                        type = 'difference',
                        cov_val1="1.0",cov_val2="0.0")
```

```{r filtered and relative effects}
### TIDY UP THE RESULTS AND MAKE GRAPHS ###
# forest plots gender x control x topic (topics ordered by prevalence)

# match the full dataset to topic names - exclude irrelevant

# add topic names for all included topics
# add mean proportions for all included topics if we want to see relative difference
# filter to climate justice topics
effects1_f <- effects1 %>%
  filter(topic %in% cj_topics)
effects1_f <- merge(effects1_f, transformed_df, by = "topic")
effects1_f$relativedifference <- effects1_f$difference/effects1_f$mean_proportion
effects1_f$relativelower <- effects1_f$lower/effects1_f$mean_proportion
effects1_f$relativeupper <- effects1_f$upper/effects1_f$mean_proportion
effects1_f <- merge(effects1_f, topic_names[c("topic", "topicname")], by="topic",all.x=TRUE)

effects2_f <- effects2 %>% 
  filter(topic %in% topic_names$topic)
effects2_f <- merge(effects2_f, transformed_df, by = "topic")
effects2_f$relativedifference <- effects2_f$difference/effects2_f$mean_proportion
effects2_f$relativelower <- effects2_f$lower/effects2_f$mean_proportion
effects2_f$relativeupper <- effects2_f$upper/effects2_f$mean_proportion
effects2_f <- merge(effects2_f, topic_names[c("topic", "topicname")], by="topic",all.x=TRUE)

effects3_f <- effects3 %>%
  filter(topic %in% topic_names$topic)
effects3_f <- merge(effects3_f, transformed_df, by = "topic")
effects3_f$relativedifference <- effects3_f$difference/effects3_f$mean_proportion
effects3_f$relativelower <- effects3_f$lower/effects3_f$mean_proportion
effects3_f$relativeupper <- effects3_f$upper/effects3_f$mean_proportion
effects3_f <- merge(effects3_f, topic_names[c("topic", "topicname")], by="topic",all.x=TRUE)
```

```{r forest plot 1st author}
### VISUALISATION ###
### FOREST PLOTS ###
# save graphs in width = 800

# these values do not match the ones i have in other graphs - check
# no these effects are actually different in number and sign - why ? 
# i used exactly the same data and the same process 

# first sanity check would be to run now the same thing just for the CJ topics and compare the numbers again 

# colour all of the variables similarly - if below 0 - colour green, if above 0 colour orange

### FIRST AUTHOR DIFFERENCE ###
subt <- c("← First author predicted male            First author predicted female →")
fp1 <- ggplot(data=effects1_f, aes(x=topicname, y=relativedifference, ymin=relativelower, ymax=relativeupper)) +
  labs(title = "Mean effect of first author gender",
       subtitle = "Relative difference in topic proportion") +
  geom_pointrange(colour = wes_palette("Darjeeling1")[5], shape=18, size = 0.25) + 
  geom_hline(yintercept=0, lty=2, colour ='darkgrey') +  # add a dotted line at x=1 after flip
  coord_flip() +  # flip coordinates (puts labels on y axis)
  scale_y_continuous(limits = c(-1, 1))  +
  scale_x_discrete(expand = c(0.01, 0.01)) + 
  xlab('') + 
  ylab(subt) +
  theme(
        plot.title = element_text(hjust = 0.5, size = 17),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text.y = element_text(size = 7.5)) #+
  #geom_label(aes(label = round(relativedifference, 3), y = relativedifference), 
             #size = 1, nudge_x = 0.5, 
             #label.padding = unit(0.2, "lines"),
             #label.r = unit(0,'lines'),
             #fill = "white")
print(fp1)
ggsave("graphs/1_gender_all.png", fp1, width = 6.9, height = 9.9, dpi = 1000)
```

```{r forest plot last author}
### LAST AUTHOR DIFFERENCE ###
subt2 <- c("← Last author predicted male            Last author predicted female →")
fp2 <- ggplot(data=effects2_f, aes(x=topicname, y=relativedifference, ymin=relativelower, ymax=relativeupper)) +
  labs(title = "Mean effect of last author gender",
       subtitle = "Relative difference in topic proportion") +
  geom_pointrange(colour = wes_palette("Darjeeling1")[1], shape=18, size = 0.25) + 
  geom_hline(yintercept=0, lty=2, colour ='darkgrey') +  # add a dotted line at x=1 after flip
  coord_flip() +  # flip coordinates (puts labels on y axis)
  scale_y_continuous(limits = c(-1, 1))  +
  scale_x_discrete(expand = c(0.01, 0.01)) +
  xlab('') + 
  ylab(subt2) +
  theme(
        plot.title = element_text(hjust = 0.5, size = 17),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text.y = element_text(size = 7.5)) #+
  #geom_label(aes(label = round(relativedifference, 3), y = relativedifference), 
   #          size = 2.75, nudge_x = 0.5, 
    #         label.padding = unit(0.2, "lines"),
     #        label.r = unit(0,'lines'),
      #       fill = "white")
print(fp2)
ggsave("graphs/2_gender_all.png", fp2, width = 6.9, height = 9.9, dpi = 1000)
```

```{r forest plot full group}
### MAJORITY AUTHOR DIFFERENCE ###
subt3 <- c("← Majority author predicted male            Majority author predicted female →")
fp3 <- ggplot(data=effects3_f, aes(x=topicname, y=relativedifference, ymin=relativelower, ymax=relativeupper)) +
  labs(title = "Mean effect of majority author gender",
       subtitle = "Relative difference in topic proportion") +
  geom_pointrange(colour = wes_palette("Darjeeling1")[3], shape=18, size = 1) + 
  geom_hline(yintercept=0, lty=2, colour ='darkgrey') +  # add a dotted line at x=1 after flip
  coord_flip() +  # flip coordinates (puts labels on y axis)
  scale_y_continuous(limits = c(-0.5, 1.25))  +
  scale_x_discrete(expand = c(0.1, 0.1)) +
  xlab('') + 
  ylab(subt3) +
  theme(aspect.ratio=1,
        plot.title = element_text(hjust = 0.5, size = 14),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text.y = element_text(size = 10)) +
  geom_label(aes(label = round(relativedifference, 3), y = relativedifference), 
             size = 2.75, nudge_x = 0.5, 
             label.padding = unit(0.2, "lines"),
             label.r = unit(0,'lines'),
             fill = "white")
print(fp3)
ggsave("graphs/3_genderxcolour.png", fp3, width = 6.9, height = 6.9, dpi = 1000)
```

```{r create a document-topic matrix}
### t-SNE visuals
DTM <- make.dt(model120_1, meta = data$id)
new_col_names <- as.character(1:120)
colnames(DTM) <- new_col_names
write.csv(DTM,"DTM.csv")
```

```{r load tSNE data}
# load tSNE data
tsne = read.csv("data/tsne.csv")
tsne$first_author_gender <- factor(ifelse(tsne$first_author_female == "1.0","female",
                                          ifelse(tsne$first_author_female == "0.0","male",
                                                 "unknown")))

tsne$last_author_gender <- factor(ifelse(tsne$last_author_female == "1.0","female",
                                          ifelse(tsne$last_author_female == "0.0","male",
                                                 "unknown")))

tsne$majority_author_gender <- factor(ifelse(tsne$majority_female_binary == "1.0","female",
                                          ifelse(tsne$majority_female_binary == "0.0","male",
                                                 ifelse(tsne$majority_female_binary == "0.5","even",
                                                 "unknown"))))

# write the tSNE data into an rds
saveRDS(tsne, file = "tsne.rds")
saveRDS(data_matrix, file = "tsnemat.rds")
```

```{r create clusters for tSNE visuals}
### ADD CLUSTERS ###
tsne$topic <- gsub("Topic", "", tsne$topic)  # Remove the "Topic" part

# load the CSV file with topic names
topic_names <- read.csv("data/topiclabels_final.csv", sep = ";")
topic_names <- topic_names %>% filter(topic_names$topicname != 0)
topic_names <- topic_names %>%
  filter(is.na(as.numeric(topicname)))
topic_names <- topic_names %>%
  rename(topic = number)

# combine the comp.1 and comp.2 columns into a matrix
data_matrix <- cbind(tsne$comp.1, tsne$comp.2)

# so for the interactive plot i need the following inputs -data, tsne, data_matrix and topic_names - can we save and store these to minimise the effor within the app

# use the kmeans function to cluster the data into N clusters
kmeans_model <- kmeans(tsne[c("comp.1","comp.2")], centers = 100)

# add the cluster labels to your original dataframe
tsne$cluster <- as.factor(kmeans_model$cluster)

### ADD LABELS PER CLUSTER ### 
# group the data by cluster and topic, count the number of occurrences of each topic within each cluster, and choose the most common topic for each cluster

#tsne <- tsne %>%
  #rename(topic = topic.x)

most_common_topics <- tsne %>% 
  group_by(cluster, topic) %>% 
  summarise(count = n()) %>% 
  group_by(cluster) %>% 
  arrange(desc(count)) %>% 
  slice(1) %>% 
  ungroup() %>% 
  select(cluster, topic)

# calculate % women author per cluster

first_share_women <- tsne %>%
  group_by(cluster, first_author_female) %>%
  summarise(count_gender = n()) %>%
  group_by(cluster) %>%
  mutate(percent_female = sum(count_gender[first_author_female == "1.0"]) / sum(count_gender)) %>%
  slice(1) %>% 
  ungroup() %>% 
  select(cluster, percent_female)

first_share_women$percent_female <- round(as.numeric(first_share_women$percent_female), 3)

last_share_women <- tsne %>%
  group_by(cluster, last_author_female) %>%
  summarise(count_gender = n()) %>%
  group_by(cluster) %>%
  mutate(percent_female2 = sum(count_gender[last_author_female == "1.0"]) / sum(count_gender)) %>%
  slice(1) %>% 
  ungroup() %>% 
  select(cluster, percent_female2)

last_share_women$percent_female2 <- round(as.numeric(last_share_women$percent_female2), 3)

# majority_share_women we need to get the non binary variable values here again and calculate mean proportion of female authors per cluster

# join the most common topic for each cluster to your original dataframe
tsne <- left_join(tsne, most_common_topics, by = "cluster")
tsne <- left_join(tsne, first_share_women, by = "cluster")
tsne <- left_join(tsne, last_share_women, by = "cluster")

first_point_per_cluster <- tsne %>% 
  group_by(cluster) %>% 
  slice(1) %>% 
  ungroup()

topic_names <- topic_names[-3]

# rename number into topic
tsne <- tsne %>%
  rename(topic = topic.y)
tsne <- tsne[, -which(names(tsne) == "topic.x")]
tsne <- merge(tsne, topic_names, by = "topic", all.x=TRUE)

first_point_per_cluster <- first_point_per_cluster %>%
  rename(topic = topic.y)
first_point_per_cluster <- merge(first_point_per_cluster, topic_names, by = "topic")
first_point_per_cluster <- first_point_per_cluster %>% 
  distinct(topicname, .keep_all = TRUE)
```

```{r tSNE 1st author}
# t-SNE visuals
# create a rectangle on each of these plots
# (15,-15) (55,-15) (55,30) (15,30)
rectangle_data <- data.frame(
  x = c(0, 55, 55, 0, 0),
  y = c(-25, -25, 30, 30, -25)
)

x_min <- 0
x_max <- 55
y_min <- -25
y_max <- 30

# high resolution png image
output_file <- "/Users/dianadanilenko/Desktop/gender_climate_justice/code/graphs/tsne1.png"
width <- 11
height <- 8
resolution <- 1000

# plot
plot <- tsne %>% ggplot(aes(x = comp.1, y = comp.2)) +
  geom_point(aes(colour = first_author_gender, alpha = climatejusticescore), size = 0.5,) + 
  geom_label(data = first_point_per_cluster, aes(label = paste(topicname, " (", percent_female, ")",sep="")), size = 2, nudge_y = 0) +
  xlab("t-SNE 1") + ylab("t-SNE 2") + theme_bw() +
  labs(title = "Topical space and gender of the first author",
       subtitle = "a t-SNE visualisation of the structural topic modelling output")  +
  theme(aspect.ratio=1,
        plot.title = element_text(hjust = 0.5, size = 20),
        plot.subtitle = element_text(hjust = 0.5)) + theme(text = element_text(size = 15)) +
  scale_color_manual(values=c (wes_palette("Darjeeling1")[4],wes_palette("Darjeeling1")[5],"darkgrey")) + guides(color = guide_legend(override.aes = list(size = 2.5))) + guides(alpha = guide_legend(override.aes = list(size = 2.5))) +
    annotate("rect", xmin = x_min, xmax = x_max, ymin = y_min, ymax = y_max, 
           color = "black", fill = NA, linewidth = 0.5)

# save the plot
ggsave(output_file, plot, width = width, height = height, dpi = resolution)

# maybe we only want to display labels for these clusters where a share of women is above average?
# i have all the labels we want per cluster - we just need to figure out a good way to disoplay them
```

```{r tSNE last author}
# high resolution png image
output_file <- "/Users/dianadanilenko/Desktop/gender_climate_justice/code/graphs/tsne2.png"
width <- 11
height <- 8
resolution <- 1000

# plot
plot <- tsne %>% ggplot(aes(x = comp.1, y = comp.2)) +
  geom_point(aes(colour = last_author_gender, alpha = climatejusticescore), size = 0.5,) + 
  geom_label(data = first_point_per_cluster, aes(label = paste(topicname, " (", percent_female2, ")",sep="")), size = 2, nudge_y = 0) +
  xlab("t-SNE 1") + ylab("t-SNE 2") + theme_bw() +
  labs(title = "Topical space and gender of the last author",
       subtitle = "a t-SNE visualisation of the structural topic modelling output")  +
  theme(aspect.ratio=1,
        plot.title = element_text(hjust = 0.5, size = 20),
        plot.subtitle = element_text(hjust = 0.5)) + theme(text = element_text(size = 15)) +
  scale_color_manual(values=c (wes_palette("Darjeeling1")[4],wes_palette("Darjeeling1")[5],"darkgrey")) + guides(color = guide_legend(override.aes = list(size = 2.5))) + guides(alpha = guide_legend(override.aes = list(size = 2.5))) + 
  annotate("rect", xmin = x_min, xmax = x_max, ymin = y_min, ymax = y_max, 
           color = "black", fill = NA, linewidth = 0.5)

# save the plot
ggsave(output_file, plot, width = width, height = height, dpi = resolution)
```

```{r tSNE full group}
# high resolution png image
output_file <- "/Users/dianadanilenko/Desktop/gender_climate_justice/code/graphs/tsne3.png"
width <- 11
height <- 8
resolution <- 1000

# plot
plot <- tsne %>% ggplot(aes(x = comp.1, y = comp.2)) +
  geom_point(aes(colour = majority_author_gender, alpha = climatejusticescore), size = 0.5,) + 
  geom_label(data = first_point_per_cluster, aes(label = topicname), size = 2, nudge_y = 0) +
  xlab("t-SNE 1") + ylab("t-SNE 2") + theme_bw() +
  labs(title = "Topical space and gender composition of the full author group",
       subtitle = "a t-SNE visualisation of the structural topic modelling output")  +
  theme(aspect.ratio=1,
        plot.title = element_text(hjust = 0.5, size = 20),
        plot.subtitle = element_text(hjust = 0.5)) + theme(text = element_text(size = 15)) +
  scale_color_manual(values=c (wes_palette("Darjeeling1")[3] ,wes_palette("Darjeeling1")[4],wes_palette("Darjeeling1")[5], "darkgrey")) + guides(color=guide_legend(order = 1, override.aes=list(size=2.5)), alpha=guide_legend(order = 0, override.aes=list(size=2.5))) + 
      annotate("rect", xmin = x_min, xmax = x_max, ymin = y_min, ymax = y_max, 
           color = "black", fill = NA, linewidth = 0.5)

# for this one we could add an average proportion female
# save the plot
ggsave(output_file, plot, width = width, height = height, dpi = resolution)
```

```{r tSNE zoom last author}
### t-SNE ZOOMED-IN SNAPSHOTS ###
# filter the data by coordinate values
# t-SNE 1 > 0
# 30 > t-SNE 2 > -25

# another idea would be to identify clusters with lowest and highest shares and make zooms of those
# there is somehow an artificial white border but setting xlim and ylim doesn't change it

tsne_zoom <- tsne %>%
  filter(comp.1 > 0 & comp.2 > -25 & comp.2 < 30)

first_point_zoom <- first_point_per_cluster %>%
  filter(comp.1 > 0 & comp.2 > -25 & comp.2 < 30)

# high resolution png image
output_file <- "/Users/dianadanilenko/Desktop/gender_climate_justice/code/graphs/tsne2_zoom.png"
width <- 11
height <- 8
resolution <- 1000

# try implementing these in plotly - we could then use DASH for interactive visuals

# plot
plot <- tsne_zoom %>% ggplot(aes(x = comp.1, y = comp.2)) +
  geom_point(aes(colour = last_author_gender, alpha = climatejusticescore), size = 1.5,) + 
  geom_label(data = first_point_zoom, aes(label = paste(topicname, " (", percent_female2, ")",sep="")), size = 3.5, nudge_y = 0, nudge_x = 1) + 
  #xlim(16,53) + ylim(-15,30) +
     scale_x_continuous(limits = c(0, 55), expand = c(0, 0)) +
     scale_y_continuous(limits = c(-25, 30), expand = c(0, 0)) +
  xlab("") + ylab("") + theme_bw() +
  #labs(title = "Topical space and gender of the last author",
   #    subtitle = "a t-SNE visualisation of the structural topic modelling output")  +
  theme(aspect.ratio=1,
        plot.title = element_text(hjust = 0.5, size = 20),
        plot.subtitle = element_text(hjust = 0.5)) + theme(text = element_text(size = 15)) +
  scale_color_manual(values=c (wes_palette("Darjeeling1")[4],wes_palette("Darjeeling1")[5],"darkgrey")) + 
  guides(color = guide_legend(override.aes = list(size = 2.5))) + 
  guides(alpha = guide_legend(override.aes = list(size = 2.5)))

# save the plot
ggsave(output_file, plot, width = width, height = height, dpi = resolution)
```

```{r tSNE zoom first author}
# high resolution png image
output_file <- "/Users/dianadanilenko/Desktop/gender_climate_justice/code/graphs/tsne1_zoom.png"
width <- 11
height <- 8
resolution <- 1000

# to make this readable we need to add a rectangle to the main plot outlining where this belongs

# plot
plot <- tsne_zoom %>% ggplot(aes(x = comp.1, y = comp.2)) +
  geom_point(aes(colour = first_author_gender, alpha = climatejusticescore), size = 1.5,) + 
  geom_label(data = first_point_zoom, aes(label = paste(topicname, " (", percent_female, ")",sep="")), size = 3.5, nudge_y = 0, nudge_x = 1) +
  xlab("") + ylab("") + theme_bw() +
       scale_x_continuous(limits = c(0, 55), expand = c(0, 0)) +
     scale_y_continuous(limits = c(-25, 30), expand = c(0, 0)) +
 # labs(title = "Topical space and gender of the first author",
  #     subtitle = "a t-SNE visualisation of the structural topic modelling output")  +
  theme(aspect.ratio=1,
        plot.title = element_text(hjust = 0.5, size = 20),
        plot.subtitle = element_text(hjust = 0.5)) + theme(text = element_text(size = 15)) +
  scale_color_manual(values=c (wes_palette("Darjeeling1")[4],wes_palette("Darjeeling1")[5],"darkgrey")) + guides(color = guide_legend(override.aes = list(size = 2.5))) + guides(alpha = guide_legend(override.aes = list(size = 2.5)))

# save the plot
ggsave(output_file, plot, width = width, height = height, dpi = resolution)
```

```{r tSNE zoom full group}
# high resolution png image
output_file <- "/Users/dianadanilenko/Desktop/gender_climate_justice/code/graphs/tsne3_zoom.png"
width <- 11
height <- 8
resolution <- 1000

# to make this readable we need to add a rectangle to the main plot outlining where this belongs

# plot
plot <- tsne_zoom %>% ggplot(aes(x = comp.1, y = comp.2)) +
  geom_point(aes(colour = majority_author_gender, alpha = climatejusticescore), size = 1.5,) + 
  geom_label(data = first_point_zoom, aes(label = paste(topicname)), size = 3.5, nudge_y = 0, nudge_x = 2) +
  xlab("") + ylab("") + theme_bw() +
       scale_x_continuous(limits = c(0, 55), expand = c(0, 0)) +
     scale_y_continuous(limits = c(-25, 30), expand = c(0, 0)) +
  #labs(title = "Topical space and gender of the full author group",
    #   subtitle = "a t-SNE visualisation of the structural topic modelling output")  +
  theme(aspect.ratio=1,
        plot.title = element_text(hjust = 0.5, size = 20),
        plot.subtitle = element_text(hjust = 0.5)) + theme(text = element_text(size = 15)) +
  scale_color_manual(values=c (wes_palette("Darjeeling1")[3],wes_palette("Darjeeling1")[4],wes_palette("Darjeeling1")[5],"darkgrey")) + guides(color = guide_legend(order = 1,override.aes = list(size = 2.5))) + guides(alpha = guide_legend(order = 0,override.aes = list(size = 2.5)))

# save the plot
ggsave(output_file, plot, width = width, height = height, dpi = resolution)
```

```{r beta regression aggregate}
### EXTERNAL REGRESSION ANALYSIS ###

# this will omit topic score uncertainty - unless we can pull that from the stm output and do uncertainty simulations

### ANALYSIS OF CONTROL VARIABLE EFFECTS / INTERACTIONS ### 

# run a beta regression with logit link
# outcome - CJ score (continuous between 0 and 1)
# predictors - use the same formula as above for prep1, prep2 and prep3
data1 <- read.csv("data/data_2311.csv", header=TRUE)

data <- merge(data, tsne[c('id', 'climatejusticescore')], by='id')

# excluding subfield here as it has too many levels

model1_y <- betareg(climatejusticescore ~first_author_female + year + #subfield 
                      X1_gii_quartile + impact + 
                      #subfield*first_author_female +     
                      impact*first_author_female +
                      X1_gii_quartile*first_author_female, data = data)

summary(model1_y)
# visualise this nicely
```

```{r heatmap}
### create a heatmap - CJ topic x continent

data_complete <- read.csv("data/data_complete.csv", header = TRUE)
dplyr::count(data, X1_country, sort = TRUE)
dplyr::count(data, X1_region, sort = TRUE)
dplyr::count(data, world_region)

data_cj <- data %>% filter(topic %in% cj_topics)
# 7517 observations

# add a value for each combination in the dataset
data_cj <- data_cj %>%
  group_by(X1_region, topicname) %>%
  mutate(value = n())
data_cj$value <- as.numeric(data_cj$value)

mat1 <- data_cj[c("X1_region","topicname","value")]

# deduplicate

mat2 <- mat1 %>%
  group_by(topicname) %>%
  summarize(value = first(value)) %>%
  pivot_wider(names_from = topicname, values_from = value)
mat2 <- mat2[-2]
mat2 <- mat2 %>%
  group_by(X1_region) %>%
  summarize_all(~ ifelse(all(is.na(.)), NA, na.omit(.)))
mat2 <- as.data.frame(mat2)
rownames(mat2) <- mat2$X1_region
mat2 <- mat2 %>% dplyr::select(-X1_region)
mat2 <- as.matrix(mat2)
mat2[is.na(mat2)] <- 0
tmat2 <- t(mat2)
```

```{r heatmap dominant topic}
p <- heatmaply(percentize(mat2),
        dendrogram = "none",
        cellnote = mat2,
        xlab = "", ylab = "", 
        main = "",
        colors = wes_palette("Zissou1"),
        #scale = "column",
        #margins = c(60,100,40,20),
        grid_color = "white",
        grid_width = 0.00001,
        titleX = FALSE,
        hide_colorbar = FALSE,
        branches_lwd = 0.1,
        label_names = c("Topic", "Region", "Documents"),
        fontsize_row = 7, fontsize_col = 7,
        labCol = colnames(mat2),
        labRow = rownames(mat2),
        heatmap_layers = theme(axis.line=element_blank()))
p

# here, we count only the most prominent topic in a document
# next step would be to count all the documents above a threshold

```

```{r data processing}
# cleaning data
# we want a neat table of all document info and corresponding topic proportions for each topic
dtm <- read.csv("data/DTM.csv")
dtm <- dtm %>% rename(id = meta)
dtm <- dtm %>% dplyr::select(-docnum)
new_names <- gsub("Topic", "",colnames(dtm))
colnames(dtm) <- new_names

data$X1_continent <- countryname(data$X1_country, destination = "continent", warn = TRUE)
data$X1_region <- countryname(data$X1_country, destination = "region", warn = TRUE)
data$X1_iso3 <- countryname(data$X1_country, destination = "iso3c", warn = TRUE)
data$X1_region <- as.factor(data$X1_region)

data$X2_continent <- countryname(data$X2_country, destination = "continent", warn = TRUE)
data$X2_region <- countryname(data$X2_country, destination = "region", warn = TRUE)
data$X2_iso3 <- countryname(data$X2_country, destination = "iso3c", warn = TRUE)
data$X2_region <- as.factor(data$X2_region)

data <- merge(data, tsne[c('id', 'topic',"climatejusticescore")], by='id', all.x = TRUE)
data$topic <- as.numeric(gsub("Topic", "", data$topic))

data <- merge(data, topic_names[c('topic', 'topicname')], by='topic', all.x = TRUE)

data <- merge(data, dtm, by='id', all.x = TRUE)

write.csv(data,"data_complete.csv")
# this file contains all documents with their ids, metadata, and all necessary STM information
# a separate file contains tsne data
```

```{r data climate justice mean}
data_cj_mean <- read.csv('data/data_cj_mean.csv', header = TRUE) 
data_cj_mean <- data_cj_mean %>% dplyr::slice(-(1:2))
rownames(data_cj_mean) <- data_cj_mean$X
data_cj_mean <- data_cj_mean %>% dplyr::select(-X,-climatejusticescore)
colnames(data_cj_mean) <- cj_topicnames
data_cj_mean <- data_cj_mean %>%
  dplyr::mutate_all(~round(as.numeric(.), 4))
```

```{r count N documents "representative" of selected topics per region}
# for each CJ topic - display documents above a certain threshold

# choose all documents that have a topic score twice above average

columns_to_filter <- c("12", "21", "25", "37", "44", "50", "56", "80", "83", "91", "101", "118", "119")
filtered_data_list <- list()
colnames(mean_proportions_f) <- cj_topicnames

for (col_name in cj_topicnames) {
  filtered_data_list[[col_name]] <- data %>%
    filter(.data[[col_name]] > 2 * mean_proportions_f[[col_name]]) %>%
    mutate(Topic = col_name)  # Add a column indicating the topic number
}

# this an arbitrary decision - one can move the threshold
consolidated_data <- bind_rows(filtered_data_list)
rownames(consolidated_data) <- NULL

# add number of documents per region (based on the first author's institutional affiliation)

result <- consolidated_data %>%
  count(X1_region, Topic)
# add divison by overall count
result <- result %>%
  rename("Documents" = n)

# write this into a matrix shape

mat3 <- result %>%
  pivot_wider(names_from = X1_region, values_from = "Documents")
mat3 <- as.data.frame(mat3)
mat3 <- mat3 %>%
  rename(topic = Topic)
#mat3 <- merge(mat3,topic_names[c("topic","topicname")],by='topic')
rownames(mat3) <- mat3$topic
mat3 <- mat3[-1]

mat3 <- mat3[-9]
mat3$World <- rowSums(mat3, na.rm = TRUE)

mat3 <- arrange(mat3, World)

```

```{r heatmap x count x first author affiliation}
p <- heatmaply(percentize(mat3),
        dendrogram = "none",
        cellnote = mat3,
        xlab = "", ylab = "", 
        main = "",
        colors = wes_palette("Zissou1"),
        grid_color = "white",
        grid_width = 0.1,
        titleX = FALSE,
        hide_colorbar = FALSE,
        branches_lwd = 0.5,
        label_names = c("Topic", "Region", "Document Count (%)"),
        fontsize_row = 10, fontsize_col = 10,
        labCol = colnames(mat3),
        labRow = rownames(mat3),
        heatmap_layers = theme(axis.line=element_blank(), aspect.ratio=1))
p

# this graph actually shows some interesting results
# most prominent topic in east asia and europe is adaptive capacity, migration, europe - transformation discourse; latin america and middle east - vulnerability, social capital, local knowledge; north america - migration, adaptive capacity, transformation discourse; south asia and subsaharan africa - rural households, food security, vulnerability, adaptive capacity
# least prominent topics - across continents apart for latin america - island territories; rural households - apart for south asia and sub-saharan africa
# this means these topics are generally vastly underrepresented in the discourse  
```

```{r heatmap x share x first author affiliation}
# for each CJ topic - display documents above a certain threshold
# choose all documents that are above average
columns_to_filter <- c("12", "21", "25", "37", "44", "50", "56", "80", "83", "91", "101", "118", "119")
filtered_data_list <- list()

for (col_name in cj_topicnames) {
  filtered_data_list[[col_name]] <- data %>%
    filter(.data[[col_name]] > 2 * mean_proportions_f[[col_name]]) %>%
    mutate(Topic = col_name)  # Add a column indicating the topic number
}

consolidated_data <- bind_rows(filtered_data_list)

rownames(consolidated_data) <- NULL

# add number of documents per region - and then create a heatmap
region_counts <- as.data.frame(table(data$X1_region))
region_counts <- region_counts %>%
  rename("X1_region" = Var1)

result <- consolidated_data %>%
  filter(X1_region != "Unknown") %>%
  count(X1_region, Topic) 

# divide the count by the overall number of documents in this region 

result <- result %>%
  rename("Documents" = n)
result <- merge(result, region_counts, by="X1_region", all.x=TRUE)
result$relative <- 100*round(result$Documents / result$Freq, 4)
result <- result %>%
  select(-Documents,-Freq)

# create a matrix

mat4 <- result %>%
  pivot_wider(names_from = X1_region, values_from = "relative")
mat4 <- as.data.frame(mat4)
mat4 <- mat4 %>%
  rename(topic = Topic)
rownames(mat4) <- mat4$topic
mat4 <- mat4[-1]
                   
mat4$World <- matg$World

mat4 <- arrange(mat4, World)
mat4 <- mat4%>%
  select(-World)

p <- heatmaply(percentize(mat4, axis = 2),
        dendrogram = "none",
        cellnote = mat4,
        xlab = "", ylab = "", 
        main = "",
        colors = wes_palette("Zissou1"),
        grid_color = "white",
        grid_width = 0.1,
        titleX = FALSE,
        hide_colorbar = FALSE,
        branches_lwd = 0.5,
        label_names = c("Topic", "Region", "Document Count (%)"),
        fontsize_row = 10, fontsize_col = 10,
        labCol = colnames(mat4),
        labRow = rownames(mat4),
        heatmap_layers = theme(axis.line=element_blank(), aspect.ratio=1))
p
```

```{r heatmap x share x last author affiliation}
filtered_data_list <- list()

for (col_name in cj_topicnames) {
  filtered_data_list[[col_name]] <- data %>%
    filter(.data[[col_name]] > 2 * mean_proportions_f[[col_name]]) %>%
    mutate(Topic = col_name)  # Add a column indicating the topic number
}

consolidated_data <- bind_rows(filtered_data_list)

rownames(consolidated_data) <- NULL

# add number of documents per region - and then create a heatmap
region_counts <- as.data.frame(table(data$X2_region))
region_counts <- region_counts %>%
  rename("X2_region" = Var1)

result2 <- consolidated_data %>%
  filter(X2_region != "Unknown") %>%
  count(X2_region, Topic) 

# divide the count by the overall number of documents in this region 

result2 <- result2 %>%
  rename("Documents" = n)
result2 <- merge(result2, region_counts, by="X2_region", all.x=TRUE)
result2$relative <- 100*round(result2$Documents / result2$Freq, 4)
result2 <- result2 %>%
  select(-Documents,-Freq)

# create a matrix

mat5 <- result2 %>%
  pivot_wider(names_from = X2_region, values_from = "relative")
mat5 <- as.data.frame(mat5)
mat5 <- mat5 %>%
  rename(topic = Topic)
rownames(mat5) <- mat5$topic
mat5 <- mat5[-1]
                   
mat5$World <- matg$World

mat5 <- arrange(mat5, World)
mat5 <- mat5%>%
  select(-World)

p <- heatmaply(percentize(mat5, axis = 2),
        dendrogram = "none",
        cellnote = mat5,
        xlab = "", ylab = "", 
        main = "",
        colors = wes_palette("Zissou1"),
        grid_color = "white",
        grid_width = 0.1,
        titleX = FALSE,
        hide_colorbar = FALSE,
        branches_lwd = 0.5,
        label_names = c("Topic", "Region", "Document Count (%)"),
        fontsize_row = 10, fontsize_col = 10,
        labCol = colnames(mat5),
        labRow = rownames(mat5),
        heatmap_layers = theme(axis.line=element_blank(), aspect.ratio=1))
p

```

```{r heatmap by topic - redundant}
mat3 <- mat3[-9]
mat5 <- t(mat4)

# in general, these do not seem to be very insightful 
# this one makes more sense than others but i would struggle to interpret this? 

p <- heatmaply(percentize(mat5),
        dendrogram = "none",
        cellnote = round(mat5, digits=2),
        xlab = "", ylab = "", 
        main = "",
        colors = wes_palette("Zissou1"),
        grid_color = "white",
        grid_width = 0.1,
        titleX = FALSE,
        hide_colorbar = FALSE,
        branches_lwd = 0.5,
        label_names = c("Topic", "Region", "Document Count (%)"),
        fontsize_row = 10, fontsize_col = 10,
        labCol = colnames(mat5),
        labRow = rownames(mat5),
        heatmap_layers = theme(axis.line=element_blank()),
        height=1,
        width=1)
p
```

```{r heatmap by topic - redundant}
# this doesn't make sense
p <- heatmaply(percentize(mat6),
        dendrogram = "none",
        cellnote = round(mat6, digits=2),
        xlab = "", ylab = "", 
        main = "",
        colors = wes_palette("Zissou1"),
        grid_color = "white",
        grid_width = 0.1,
        titleX = FALSE,
        hide_colorbar = FALSE,
        branches_lwd = 0.5,
        label_names = c("Topic", "Region", "Document Count (%)"),
        fontsize_row = 10, fontsize_col = 10,
        labCol = colnames(mat6),
        labRow = rownames(mat6),
        heatmap_layers = theme(axis.line=element_blank(), aspect.ratio=1))
p

```

```{r matrix of relative topic shares}
# create a matrix of relative topic shares 
mat6 <- mat3

topics_rows <- 1:(nrow(mat6))
world_column <- ncol(mat6)

for (row in topics_rows) {
  mat6[row, 1:(world_column - 1)] <- mat6[row, 1:(world_column - 1)] / mat6[row, world_column]
}
mat6 <- mat6[-9]
mat6 <- t(mat6)
```

```{r heatmap x count x geoparsed location}
data_g <- read.csv("data/df_geoparsed.csv", header=TRUE)
# what do we actually need to create a heatmap 
# region x topic - number / share of documents where topic score is above 2*mean

# add number of documents per region (geoparsed)
result_g <- consolidated_data %>%
  filter(! is.na (world_region)) %>%
  separate_rows(world_region, sep=";") %>%
  count(world_region, Topic)

# add divison by overall count
result_g <- result_g %>%
  rename("Documents" = n)

# write this into a matrix shape - geoparsed
matg <- result_g %>%
  pivot_wider(names_from = world_region, values_from = "Documents")
matg <- as.data.frame(matg)
matg <- matg %>%
  rename(topic = Topic)
rownames(matg) <- matg$topic
matg <- matg[-1]

matg$World <- rowSums(matg, na.rm = TRUE)

matg <- arrange(matg, World)
matg <- matg%>%
  select(-World)

p <- heatmaply(percentize(matg),
        dendrogram = "none",
        cellnote = matg,
        xlab = "", ylab = "", 
        main = "",
        colors = wes_palette("Zissou1"),
        grid_color = "white",
        grid_width = 0.1,
        titleX = FALSE,
        hide_colorbar = FALSE,
        branches_lwd = 0.5,
        label_names = c("Topic", "Region", "Document Count (%)"),
        fontsize_row = 10, fontsize_col = 10,
        labCol = colnames(matg),
        labRow = rownames(matg),
        heatmap_layers = theme(axis.line=element_blank(), aspect.ratio=1))
p
```

```{r heatmap x share x geoparsed location}

# overall N documents per region

result_gS <- data %>%
  filter(! is.na (world_region)) %>%
  separate_rows(world_region, sep=";") %>%
  count(world_region)

result_g_share <- consolidated_data %>%
  filter(! is.na (world_region)) %>%
  separate_rows(world_region, sep=";") %>%
  count(world_region, Topic) 

# divide the count by the overall number of documents in this region 

result_g_share <- result_g_share %>%
  rename("Documents" = n)
result_g_share <- merge(result_g_share, result_gS,by="world_region", all.x=TRUE)
result_g_share$relative <- 100*round(result_g_share$Documents / result_g_share$n, 4)
result_g_share <- result_g_share %>%
  select(-Documents,-n)

# create a matrix

matgs <- result_g_share %>%
  pivot_wider(names_from = world_region, values_from = "relative")
matgs <- as.data.frame(matgs)
matgs <- matgs %>%
  rename(topic = Topic)
rownames(matgs) <- matgs$topic
matgs <- matgs[-1]

matgs$World <- rowSums(matgs, na.rm = TRUE)

matgs <- arrange(matgs, World)
matgs <- matgs%>%
  select(-World)

# create a heatmap

p <- heatmaply(percentize(matgs),
        dendrogram = "none",
        cellnote = matgs,
        xlab = "", ylab = "", 
        main = "",
        colors = wes_palette("Zissou1"),
        grid_color = "white",
        grid_width = 0.1,
        titleX = FALSE,
        hide_colorbar = FALSE,
        branches_lwd = 0.5,
        label_names = c("Topic", "Region", "Document Count (%)"),
        fontsize_row = 10, fontsize_col = 10,
        labCol = colnames(matgs),
        labRow = rownames(matgs),
        heatmap_layers = theme(axis.line=element_blank(), aspect.ratio=1))
p
```

```{r share female authors per world region}
data <- read.csv("data/data_complete.csv", header=TRUE)
# count first_author_female per each X1_region 
# count last_author_female per each X2_region
data$first_author_female <- as.numeric(data$first_author_female)
data$last_author_female <- as.numeric(data$last_author_female)

result_1 <- data %>%
  group_by(X1_region) %>%
  summarize(
    share_female_first = sum(first_author_female == 1.0 & !is.na(first_author_female)) / sum(!is.na(first_author_female))
  )

result_1 <- result_1 %>% filter(X1_region != "Unknown")

result_2 <- data %>%
  group_by(X2_region) %>%
  summarize(
    share_female_last = sum(last_author_female == 1.0 & !is.na(last_author_female)) / sum(!is.na(last_author_female))
  )
result_2 <- result_2 %>% filter(X2_region != "Unknown")

ggplot(result_1, aes(x = X1_region, y = share_female_first)) +
    geom_hline(yintercept=0.3883, alpha=0.75, linetype="dashed", color="red") +
  annotate("text", x="Sub-Saharan Africa", y = 0.3883 + 0.025, label = "Total: 38.83%") +
  geom_bar(stat = "identity", fill = wes_palette("Darjeeling1")[4], color = "darkgrey", alpha = 1) +
  geom_label(aes(label = paste0(round(share_female_first, digits=4) * 100, "%")), position = position_stack(vjust = 0.5), size=4) +
  labs(title = "Share of female first authors by world region",
       x = NULL,
       y = NULL) +
  theme_minimal() + ylim(0,0.5) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
ggsave("graphs/share_fem_first.png", width=6.9, height=6.9, dpi=1000)

ggplot(result_2, aes(x = X2_region, y = share_female_last)) +
  geom_hline(yintercept=0.2881, alpha=0.75, linetype="dashed", color="red") + 
  annotate("text", x="Sub-Saharan Africa", y = 0.2881 + 0.025, label = "Total: 28.81%") +
  geom_bar(stat = "identity", fill = wes_palette("Darjeeling1")[4], color = "darkgrey", alpha = 1) +
  geom_label(aes(label = paste0(round(share_female_last, digits=4) * 100, "%")), position = position_stack(vjust = 0.5), size=4) +
  labs(title = "Share of female last authors by world region",
       x = NULL,
       y = NULL) +
  theme_minimal() + ylim(0,0.5) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
ggsave("graphs/share_fem_last.png", width=6.9, height=6.9, dpi=1000)

```

```{r share documents on justice per world region}
# first summarise by region
# then summarise by first / last / majority author gender
# if any of justice topics > 2*mean justice = 1, otherwise = 0 

# update these graphs - what would be a more meaningful share ? 

data <- data %>% 
  select(-X)
columns_to_rename <- grep("^X\\d+$", colnames(data))  # identify columns starting with X and followed by digits
# rename selected columns
colnames(data)[columns_to_rename] <- as.character(1:120)

columns_to_filter <- c("12", "21", "25", "37", "44", "50", "56", "80", "83", "91", "101", "118", "119")

data$justice <- ifelse(rowSums(data[, columns_to_filter, drop = FALSE] > 2*colMeans(data[, columns_to_filter], na.rm = TRUE), na.rm = TRUE) > 0, 1, 0)

data <- merge(data, data_g_f[c("id", "world_region")], by="id",all.x=TRUE)
write.csv(data,"data/data_30_01_24.csv")

summary(data$justice)
# 0.681 is quite a high number - i dont know if this really makes sense
# it goes to 0.4602 if we say "justice" paper should include at least an intersection of two of these topics but that would be a very arbitrary claim
# 0.3027

# first author gender x institutional affiliation
result_3 <- data %>%
  filter(first_author_female != "unknown") %>%
  group_by(X1_region, first_author_female) %>%
  summarize(
    share_justice = sum(justice == 1.0 & !is.na(justice)) / sum(!is.na(justice))
  )
result_3 <- result_3 %>% filter(X1_region != "Unknown")


ggplot(result_3, aes(x = X1_region, y = share_justice, fill = factor(first_author_female))) +
  geom_hline(yintercept = 0.681, alpha=0.75, linetype="dashed", color="red") +
  annotate("text", x="Middle East & North Africa", y = 0.681 + 0.05, label = "Mean: 68.1%") +
  geom_bar(width=.69, stat = "identity", position = position_dodge(0.85), color = "darkgrey") +
  labs(title = "Share of documents on climate justice by world region and first author gender",
       x = NULL,
       y = "Share of documents related to at least 1 justice topic") +
  scale_fill_manual(values = c(wes_palette("Darjeeling1")[5], wes_palette("Darjeeling1")[4]), name = "Author's Gender",
                    labels = c("Male", "Female")) +
  theme_minimal() + ylim(0, 1) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
ggsave("graphs/share_justice_first(2).png", width=9.9, height=6.9, dpi=1000)

# last author gender x institutional affiliation
result_4 <- data %>%
  filter(!is.na(last_author_female)) %>%
  group_by(X2_region, last_author_female) %>%
  summarize(
    share_justice = sum(justice == 1.0 & !is.na(justice)) / sum(!is.na(justice))
  )
result_4 <- result_4 %>% filter(X2_region != "Unknown")

ggplot(result_4, aes(x = X2_region, y = share_justice, fill = factor(last_author_female))) +
  geom_hline(yintercept = 0.681, alpha=0.75, linetype="dashed", color="red") +
 # annotate("text", x="Middle East & North Africa", y = 0.4602 + 0.05, label = "46.02%") +
  geom_bar(width=.69, stat = "identity", position = position_dodge(.85), color = "darkgrey") +
  labs(title = "Share of documents on climate justice by world region and last author gender",
       x = NULL,
       y = "Share of documents related to at least 1 justice topic") +
  scale_fill_manual(values = c(wes_palette("Darjeeling1")[5], wes_palette("Darjeeling1")[4]), name = "Author's Gender",
                    labels = c("Male", "Female")) +
  theme_minimal() + ylim(0, 1) + theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
ggsave("graphs/share_justice_last(2).png", width=9.9, height=6.9, dpi=1000)

# first author gender x geoparsed location
result_5 <- data %>%
  filter(!is.na(first_author_female)) %>% 
  separate_rows(world_region, sep=";") %>%
  group_by(world_region, first_author_female) %>%
  summarize(
    share_justice = sum(justice == 1.0 & !is.na(justice)) / sum(!is.na(justice))
  )
result_5 <- result_5 %>% 
  filter(! is.na(world_region))

ggplot(result_5, aes(x = world_region, y = share_justice, fill = factor(first_author_female))) +
  geom_hline(yintercept = 0.681, alpha=0.75, linetype="dashed", color="red") +
  #annotate("text", x="Middle East & North Africa", y = 0.4602 + 0.05, label = "46.02%") +
  geom_bar(width=.69, stat = "identity", position = position_dodge(.85), color = "darkgrey") +
  labs(title = "Share of documents on climate justice by world region (location from text) and first author gender",
       x = NULL,
       y = "Share of documents related to at least 1 justice topics") +
  scale_fill_manual(values = c(wes_palette("Darjeeling1")[5], wes_palette("Darjeeling1")[4]), name = "Author's Gender",
                    labels = c("Male", "Female")) +
  theme_minimal() + ylim(0, 1) + theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
ggsave("graphs/share_justice_first_geoparsed(2).png", width=9.9, height=6.9, dpi=1000)

# last author gender x geoparsed location
result_6 <- data %>%
  filter(!is.na(last_author_female)) %>%
  separate_rows(world_region, sep=";") %>%
  group_by(world_region, last_author_female) %>%
  summarize(
    share_justice = sum(justice == 1.0 & !is.na(justice)) / sum(!is.na(justice))
  )
result_6 <- result_6 %>%
  filter(!is.na(world_region))

ggplot(result_6, aes(x = world_region, y = share_justice, fill = factor(last_author_female))) +
  geom_hline(yintercept = 0.681, alpha=0.75, linetype="dashed", color="red") +
# annotate("text", x="Middle East & North Africa", y = 0.4602 + 0.05, label = "46.02%") +
  geom_bar(width=.69, stat = "identity", position = position_dodge(.85), color = "darkgrey") +
  labs(title = "Share of documents on climate justice by world region (location from text) and last author gender",
       x = NULL,
       y = "SShare of documents related to at least 1 justice topic") +
  scale_fill_manual(values = c(wes_palette("Darjeeling1")[5], wes_palette("Darjeeling1")[4]), name = "Author's Gender",
                    labels = c("Male", "Female")) +
  theme_minimal() + ylim(0, 1) + theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
ggsave("graphs/share_justice_last_geoparsed(2).png", width=9.9, height=6.9, dpi=1000)

# we could try excluding some topics, while including others (for instance, "migration" topic could well contribute to dissimintation of non-justice ideas)
```

```{r pull world region from geoparsed location}

get_continent <- function(country_code) {
  cc <- countrycode(country_code, "iso3c", "region")
  if (length(unique(cc[!is.na(cc)])) == 1) {
    return(unique(cc[!is.na(cc)]))
  } else {
    return(paste(unique(cc[!is.na(cc)]), collapse = ";"))
  }
}

data_g <- data_g %>%
  mutate(world_region = sapply(strsplit(country_code3, ";"), get_continent))

table(data_g$world_region)

data_g$world_region <- as.character(data_g$world_region)

# split the column entries by ; and see whether any repeat

data_g <- data_g %>%
  mutate(world_region = sapply(strsplit(world_region, ";"), function(x) paste(unique(x), collapse = ";")))
data_g <- data_g %>%
  mutate(repetitions = sapply(strsplit(world_region, ";"), function(x) anyDuplicated(x) > 0))

# no double-counting of articles per region is secured

data_g_f <- data_g %>% 
  filter(nchar(world_region)>0)
#25675 observations
data_g_f
# if world regions explicitly mentioned in word_x or word_y -> assign that world region directly

# Africa - Sub-Saharan Africa 
# Europe, EUROPE, EU - Europe & Central Asia
# Southeast Asia - South Asia 
# Central America - Latin America & Caribbean
# North America - North America
# Caribbean - Latin America & Caribbean
# Pacific - East Asia & Pacific
# Central Asia - Europe & Central Asia
# South America - Latin America & Caribbean  
# the Middle East - Middle East & North Africa
# Himalayas, Himalayan, Himalaya - Europe & Central Asia
# Western Europe - Europe & Central Asia
# the Iberian Peninsula - Europe & Central Asia
# the Murray-Darling Basin, Murray-Darling Basin - East Asia & Pacific
# Souther Spain - Europe & Central Asia
# South Asia - South Asia
# the Baltic Sea - Europe & Central Asia
# "North Ameericas" - North America
# Central Africa- Sub-Saharan Africa
# Sahel - Sub-Saharan Africa
# Alps - Europe & Central Asia

data_g <- data_g %>%
  mutate(world_region = case_when(
    nchar(world_region) > 0 ~ world_region, # keep the existing non-empty values
    
    str_detect(word_x, "Africa") ~ "Sub-Saharan Africa",
    str_detect(word_x, "Europe|EUROPE|EU") ~ "Europe & Central Asia",
    str_detect(word_x, "Southeast Asia") ~ "South Asia",
    str_detect(word_x, "Central America") ~ "Latin America & Caribbean",
    str_detect(word_x, "North America") ~ "North America",
    str_detect(word_x, "Caribbean") ~ "Latin America & Caribbean",
    str_detect(word_x, "Pacific") ~ "East Asia & Pacific",
    str_detect(word_x, "Central Asia") ~ "Europe & Central Asia",
    str_detect(word_x, "South America") ~ "Latin America & Caribbean",
    str_detect(word_x, "Middle East") ~ "Middle East & North Africa",
    str_detect(word_x, "Himalayas|Himalayan|Himalaya") ~ "Europe & Central Asia",
    str_detect(word_x, "Western Europe") ~ "Europe & Central Asia",
    str_detect(word_x, "Iberian Peninsula") ~ "Europe & Central Asia",
    str_detect(word_x, "Murray-Darling Basin") ~ "East Asia & Pacific",
    str_detect(word_x, "Southern Spain") ~ "Europe & Central Asia",
    str_detect(word_x, "South Asia") ~ "South Asia",
    str_detect(word_x, "Baltic Sea") ~ "Europe & Central Asia",
    str_detect(word_x, "North Americas") ~ "North America",
    str_detect(word_x, "Central Africa") ~ "Sub-Saharan Africa",
    str_detect(word_x, "Sahel") ~ "Sub-Saharan Africa",
    str_detect(word_x, "Alps") ~ "Europe & Central Asia",
    
    TRUE ~ NA_character_ # set unmatched cases to NA 
  ))
```

```{r yearly summary}
# summarise yearly:
# number of publications
# first author woman share
# last author woman share
# full group average woman share
# climate justice score 

data <- read_csv("data/data.csv")

# coerce numeric variables
data <- data %>%
  mutate(
    first_author_female = as.numeric(first_author_female),
    last_author_female = as.numeric(last_author_female),
    majority_female = as.numeric(majority_female),
    #climatejusticescore = as.numeric(climatejusticescore),
    year = as.numeric(year)
  )

# try to percentise the numbers - what do we need to divide by? 

summary_data <- data %>%
  group_by(year) %>%
  summarize(
    avg_first_author_female = sum(first_author_female, na.rm=TRUE)/sum(! is.na(first_author_female)),
    avg_last_author_female = sum(last_author_female, na.rm=TRUE)/sum(! is.na(last_author_female)),
    avg_majority_female = sum(majority_female, na.rm=TRUE)/sum(! is.na(majority_female)))

# plot 1996 to 2022
summary_data$avg_female <- summary_data$avg_first_author_female
summary_data$variable <- "first author"
summary_data <- rbind(summary_data, summary_data)
summary_data <- rbind(summary_data, summary_data)
summary_data$variable[33:64] <- "last author"
summary_data$avg_female[33:64] <- summary_data$avg_last_author_female[33:64]
summary_data$variable[65:128] <- "full group"
summary_data$avg_female[65:128] <- summary_data$avg_majority_female[65:128]
summary_data <- summary_data[-2]

rm(summary_data)

# we have to cut off here from 2006 because the data is weird otherwise probably due to very few records 
# is that okay or should we look for a different solution?

ggplot(summary_data, aes(x=year,y=avg_female, fill=variable)) + 
  geom_area(alpha=0.75 , size=.25, colour="white", position = "jitter") +
  scale_fill_manual(values=c(wes_palette("AsteroidCity1")[3],wes_palette("Darjeeling1")[3],wes_palette("AsteroidCity2")[1])) + 
  scale_y_continuous(name = "average percentage of female authors") +
  scale_x_continuous(limits = c(2007, 2022),expand=c(0,0)) + 
  theme_bw()

ggsave("graphs/femaleauthorsharetime.png", width=6.9, height=3.9, dpi=1000)

# if we are keeping this graph in this shape - it makes sense to have effects forest plots in the same colours
# there is then a bit too much colour clashes - maybe we could just add a time trend of overall % female authorships across all authorship instances in "Darjeeling1"[4]

```

```{r yearly summary 2}
# topic-specific time trend of relevant topics - would also be nice to percentise

# we need to divide the summarised topic proportions by the number of documents

summary_data2 <- data %>%
  group_by(year) %>%
  summarize(
    resilience = sum(resilience)/n(),
    food_security = sum(food_security)/n(),
    vulnerability = sum(vulnerability)/n(),
    adaptive_capacity = sum(adaptive_capacity)/n(),
    governance = sum(governance)/n(),
    local_knowledge = sum(local_knowledge)/n(),
    island_territories = sum(island_territories)/n(),
    climate_finance = sum(climate_finance)/n(),
    rural_households = sum(rural_households)/n(),
    transformation_discourse = sum(transformation_discourse)/n(),
    community = sum(community)/n(),
    social_capital = sum(social_capital)/n(),
    migration = sum(migration)/n()
  )

for (i in seq_along(cj_topics)) {
  old_name <- cj_topics[i]
  new_name <- cj_topicnames[i]
  if (old_name %in% colnames(data)) {
    colnames(data)[colnames(data) == old_name] <- new_name
  }
}

for (i in seq_along(cj_topicnames1)) {
  old_name <- cj_topicnames1[i]
  new_name <- cj_topicnames[i]
  if (old_name %in% colnames(mean_proportions_f)) {
    colnames(mean_proportions_f)[colnames(mean_proportions_f) == old_name] <- new_name
  }
}

summary_data2_long <- pivot_longer(summary_data2, cols = -year, names_to = "topic", values_to = "value")

# percentised data

columns_to_summarize <- c(
  "climatejusticescore",
  "resilience",
  "food_security",
  "vulnerability",
  "adaptive_capacity",
  "governance",
  "local_knowledge",
  "island_territories",
  "climate_finance",
  "rural_households",
  "transformation_discourse",
  "community",
  "social_capital",
  "migration"
)

summary_data3 <- data %>%
  group_by(year) %>%
  summarize(
    across(
      all_of(columns_to_summarize),
      sum,
      .names = "total_{.col}"
    )
  ) %>%
  mutate(across(
    starts_with("total_"),
    ~ . / sum(.),
    .names = "percentage_{.col}"
  ))

summary_data3 <- summary_data3 %>% select(year, starts_with("percentage_"))

summary_data3_long <- pivot_longer(summary_data3, cols = -year, names_to = "topic", values_to = "percent_value")

```

```{r yearly summary topics}
# topic-specific time trend of relevant topics - visuals
library(RColorBrewer)

ggplot(summary_data2_long, aes(x = year, y = value, fill = topic)) +
  geom_area(alpha=0.9, size=.25, colour="white") +
  labs(title = "",
       x = "year",
       y = "average topic proportion") +
  scale_x_continuous(limits = c(2007, 2021),expand=c(0,0)) +
  theme_bw() + 
  scale_fill_viridis(option = "D", discrete=T)

ggsave("graphs/topicproportiontime.png", width=6.9, height=3.9, dpi=1000)
display.brewer.all()

# topic proportion isnt normalised so isnt interpretable

ggplot(summary_data3_long, aes(x = year, y = percent_value, fill = topic)) +
  geom_area(alpha=0.9, size=.25, colour="white", position = "stack") +
  labs(title = "",
       x = "year",
       y = "topic proportion") +
  scale_x_continuous(limits = c(2006, 2023),expand=c(0,0)) +
  theme_bw() +
  scale_fill_viridis(discrete=T)
```

```{r load continuous data for relevant variables}
# get continuous data back
data <- read_csv("data/data_complete.csv")
data <- data %>%
   #select(-1) %>%
  #select(-impact) %>%
  select(-X)

gii_data <- read_excel("data/gender_inequality_index.xlsx")

data <- merge(data, gii_data, by.x="X1_country", by.y="country", all.x=T)
data <- data %>%
  rename(X1_gii = "gender inequality index")

data <- merge(data, gii_data, by.x="X2_country", by.y="country", all.x=T)
data <- data %>%
  rename(X2_gii = "gender inequality index")

data1 <- read_csv("data/df_full.csv")

data <- merge(data, data1[c('id','majority_female','impact_factor')], by='id', all.x=TRUE)

data <- data %>%
  #select(-`HDI rank.x`) %>%
  select(-`HDI rank.y`)
write.csv(data,"data/data.csv")
```

```{r load the data}
# load the full dataset
rm(data)
data <- read_csv("data/data.csv")
data <- data [ !duplicated(data$id), ]

data2311 <- read_csv("data/data_2311.csv")
data <- merge(data, data2311[c("id","broader_subfield")], all.x = TRUE, by = 'id')
rm(data2311)
write.csv(data,"data/data.csv")

data <- data %>%
  mutate(
    first_author_female = as.factor(first_author_female),
    last_author_female = as.factor(last_author_female),
    majority_female_binary = as.factor(majority_female_binary),
    climatejusticescore = as.numeric(climatejusticescore),
    X1_gii = as.numeric(X1_gii),
    impact_factor = as.numeric(impact_factor),
    year = as.numeric(year),
    broader_subfield = as.factor(broader_subfield)
  )
# data N = 42548

data1 <- data %>% 
  filter (! first_author_female == "unknown")
# data1 N = 35345

data2 <- data %>%
  filter (! last_author_female == "unknown")
# data2 N = 34329

data3 <- data %>%
  filter (! majority_female_binary == "unknown")
# data3 N = 27149

```

```{r beta regression}

# run regression diagnostics
# interaction of gender and year? 
b_reg <- betareg(climatejusticescore ~first_author_female + year +
                      X1_gii + impact_factor + 
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(b_reg)

# first_author_female1.0                0.2062644  (0.0198503)  z-value = 10.391  < 2e-16 ***

# include control of subfield and interaction
b_reg <- betareg(climatejusticescore ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(b_reg)

# first_author_female1.0                0.2275169  (0.0222547)  z-value = 10.223  < 2e-16 ***
data2 <- na.omit(data2)

b_reg2 <- betareg(
  formula = climatejusticescore ~last_author_female + year + broader_subfield + X2_gii + impact_factor + 
    broader_subfield*last_author_female + impact_factor*last_author_female + X2_gii*last_author_female, 
  data = data2,
  na.action=na.omit
)

summary(b_reg2)

# last_author_female1.0                       0.308670   0.031500   9.799  < 2e-16 ***

b_reg3 <- betareg(climatejusticescore ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(b_reg3)

# majority_female_binary1.0                       0.4335304  0.0270906  16.003  < 2e-16 ***
```

```{r beta regression per topic}
# exclude data with missing author gender variables

for (topic in cj_topicnames1) { print(topic)
  }

model1_reg <- betareg(resilience ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg)

# get the marginal effects
m1_1 <- margins(model1_reg)
# m1_1 in this case is just reproducing my original data
summary(m1_1)
# this just comes out empty
margins_summary(m1_1)

pre <- avg_predictions(model1_reg)
# what is this estimate for - which variable? 
# what i want to get out is the average estimate for each independent variable
com <- avg_comparisons(model1_reg)
# so this does actually show per variable value but only for a couple variablex x values - change limits?
mm <- marginal_means(model1_reg)
# so this is bizarre because it shows both a positive coefficient for male and female
# need to figure out how this works
plot_comparisons(model1_reg, variables = "resilience", condition = "first_author_female")

model1_reg2 <- betareg(food_security ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg2)

model1_reg3 <- betareg(vulnerability ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg3)

model1_reg4 <- betareg(adaptive_capacity ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg4)

model1_reg5 <- betareg(governance ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg5)

model1_reg6 <- betareg(local_knowledge ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg6)

model1_reg7 <- betareg(island_territories ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg7)

model1_reg8 <- betareg(climate_finance ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg8)

model1_reg9 <- betareg(rural_households ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg9)

model1_reg10 <- betareg(transformation_discourse ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg10)

model1_reg11 <- betareg(community ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg11)

model1_reg12 <- betareg(social_capital ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg12)

model1_reg13 <- betareg(migration ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(model1_reg13)
```

```{r plot a pdf of topic proportion}
# plot a pdf of a topic proportion - separate one for each gender value 
```

```{r beta regression per topic in a loop}
model_results <- list()

for (topic in cj_topicnames1) {
  topic_data <- subset(data, topic == topic)

  model1 <- betareg(topic ~ first_author_female + year +
                      X1_gii + impact_factor +
                      impact_factor * first_author_female +
                      X1_gii * first_author_female, data = topic_data)
  
  model_results[[topic]] <- summary(model1)
}
```

```{r beta regression per topic last author}
### LAST AUTHOR GENDER EXTERNAL REGRESSION ###

model2_reg <- betareg(resilience ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg)

model2_reg2 <- betareg(food_security ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg2)

model2_reg3 <- betareg(vulnerability ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg3)

model2_reg4 <- betareg(adaptive_capacity ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg4)

model2_reg5 <- betareg(governance ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg5)

model2_reg6 <- betareg(local_knowledge ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg6)

model2_reg7 <- betareg(island_territories ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg7)

model2_reg8 <- betareg(climate_finance ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg8)

model2_reg9 <- betareg(rural_households ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg9)

model2_reg10 <- betareg(transformation_discourse ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg10)

model2_reg11 <- betareg(community ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg11)

model2_reg12 <- betareg(social_capital ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg12)

model2_reg13 <- betareg(migration ~last_author_female + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*last_author_female +     
                      impact_factor*last_author_female +
                      X2_gii*last_author_female, data = data2)
summary(model2_reg13)
```

```{r beta regression per topic full group}
### MAJORITY AUTHOR GENDER EXTERNAL REGRESSION ###
data3$majority_female_binary <- as.character(data3$majority_female_binary)
data3$majority_female_binary <- if_else(data3$majority_female_binary == "0.5", "1.0",
                                         data3$majority_female_binary)
data3$majority_female_binary <- as.factor(data3$majority_female_binary)

model3_reg <- betareg(resilience ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg)

model3_reg2 <- betareg(food_security ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg2)

model3_reg3 <- betareg(vulnerability ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg3)

model3_reg4 <- betareg(adaptive_capacity ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg4)

model3_reg5 <- betareg(governance ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg5)

model3_reg6 <- betareg(local_knowledge ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg6)

model3_reg7 <- betareg(island_territories ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg7)

model3_reg8 <- betareg(climate_finance ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg8)

model3_reg9 <- betareg(rural_households ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg9)

model3_reg10 <- betareg(transformation_discourse ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg10)

model3_reg11 <- betareg(community ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg11)

model3_reg12 <- betareg(social_capital ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg12)

model3_reg13 <- betareg(migration ~majority_female_binary + year + broader_subfield +
                      X2_gii + impact_factor + 
                      broader_subfield*majority_female_binary +     
                      impact_factor*majority_female_binary +
                      X2_gii*majority_female_binary, data = data3)
summary(model3_reg13)
```

```{r beta reg post estimations}
# aggregate model
p <- plot(b_reg, which = 1:4, type = "pearson")
p <- plot(b_reg, which = 5, type = "deviance", sub.caption = "")
p <- plot(b_reg, which = 1, type = "deviance", sub.caption = "")
c <- coef(b_reg, model = "precision")

```

```{r reclassified subfields}
# reclassify subfields - but then we cannot run the stm regression - only the external one 
# and then try to get interpretable results

summary(data$subfield)
length(unique(data$subfield))
# we have 27 subfields

reclassify_subfields <- function(subfield) {
  if (subfield %in% c("Agriculture", "Environmental studies & forestry")) {
    return("Agriculture")
  } else if (subfield %in% c("Anthropology", "Business", "Economics", "Education", "Geography", "History", "Interdisciplinary", "Political science", "Psychology", "Public administration", "Sociology")) {
    return("Social Sciences")
  } else if (subfield %in% c("Biology", "Chemistry", "Earth sciences", "Mathematics", "Physics")) {
    return("Natural Sciences")
  } else if (subfield %in% "Medicine") {
    return("Health Sciences")
  } else if (subfield %in% c("Computer sciences", "Engineering & technology")) {
    return("Engineering & Technology")
  } else if (subfield %in% c("Architecture & design", "Philosophy", "Religion", "The arts")) {
    return("Arts and Humanities")
  } else if (subfield %in% "Unknown") {
    return("Unknown")
  } else if (subfield %in% "Transportation") {
    return("Engineering & Technology")
  } else {
    return("Unclassified")
  }
}

data$broader_subfield <- sapply(data$subfield, reclassify_subfields)

length(unique(data$broader_subfield))

write.csv(data, "data/data_2311.csv")

# run external regression with inclusion of broader subfield 
# check the results
```

```{r random sample blobs 1st author female}
#data <- read.csv("data/data.csv", header = TRUE)
#data <- data [ !duplicated(data$id), ]

sampled_data1_1 <- data[data$first_author_female == "1.0", ]
sampled_data1_1$climatejustice <- 0.0

colnames(mean_proportions_f) = cj_topicnames1

for (col_name in cj_topicnames1) {
  condition <- sampled_data1_1[[col_name]] > 2 * mean_proportions_f[[col_name]]
  sampled_data1_1$climatejustice[condition] <- 1.0
}

# draw a random sample of 250 rows
set.seed(2311)  
num_points <- 500

# generate random polar coordinates within a circle
theta <- runif(num_points, 0, 2 * pi)
r <- sqrt(runif(num_points))

# convert polar coordinates to Cartesian coordinates
x <- r * cos(theta)
y <- r * sin(theta)

sampled_rows1 <- sample(1:nrow(sampled_data1_1), num_points)

ggplot(data = sampled_data1_1[sampled_rows1, ], aes(x, y)) +
  geom_point(aes(alpha = climatejustice), size = 3, color = "red") +
  scale_alpha_continuous(range = c(0, 1), guide = "none") +
  theme_void() +
  coord_fixed()

```

```{r random sample blobs 1st author male}
sampled_data1_0 <- data[data$first_author_female == "0.0", ]
sampled_data1_0$climatejustice <- 0.0

# draw a random sample of 250 rows
set.seed(1713)  
num_points <- 500

# generate random polar coordinates within a circle
theta <- runif(num_points, 0, 2 * pi)
r <- sqrt(runif(num_points))

# convert polar coordinates to Cartesian coordinates
x <- r * cos(theta)
y <- r * sin(theta)

for (col_name in cj_topicnames1) {
  condition <- sampled_data1_0[[col_name]] > 2 * mean_proportions_f[[col_name]]
  sampled_data1_0$climatejustice[condition] <- 1.0
}

sampled_rows0 <- sample(1:nrow(sampled_data1_0), num_points)

ggplot(data = sampled_data1_0[sampled_rows0, ], aes(x, y)) +
  geom_point(aes(alpha = climatejustice), size = 3, color = "red") +
  scale_alpha_continuous(range = c(0, 1), guide = "none") +
  theme_void() +
  coord_fixed()

summary(sampled_data1_0[sampled_rows0, ]$climatejustice)
# climatejusticescore mean 0.1521632
# climatejustice mean 0.438

summary(sampled_data1_1[sampled_rows1, ]$climatejustice)
# mean 0.181861
# about 20% higher for women first authors
# mean 0.526
```

```{r random sample blobs last author female}
sampled_data2_1 <- data[data$last_author_female == "1.0", ]
sampled_data2_1$climatejustice <- 0.0

for (col_name in cj_topicnames1) {
  condition <- sampled_data2_1[[col_name]] > 2 * mean_proportions_f[[col_name]]
  sampled_data2_1$climatejustice[condition] <- 1.0
}

# draw a random sample of 250 rows
set.seed(1722)  
num_points <- 500

# generate random polar coordinates within a circle
theta <- runif(num_points, 0, 2 * pi)
r <- sqrt(runif(num_points))

# convert polar coordinates to Cartesian coordinates
x <- r * cos(theta)
y <- r * sin(theta)

sampled_rows2 <- sample(1:nrow(sampled_data2_1), num_points)

ggplot(data = sampled_data2_1[sampled_rows2, ], aes(x, y)) +
  geom_point(aes(alpha = climatejustice), size = 3, color = "red") +
  scale_alpha_continuous(range = c(0, 1), guide = "none") +
  theme_void() +
  coord_fixed()

```

```{r random sample blobs last author male}
sampled_data2_0 <- data[data$last_author_female == "0.0", ]
sampled_data2_0$climatejustice <- 0.0

# draw a random sample of 250 rows
set.seed(1723)  
num_points <- 500

# generate random polar coordinates within a circle
theta <- runif(num_points, 0, 2 * pi)
r <- sqrt(runif(num_points))

# convert polar coordinates to Cartesian coordinates
x <- r * cos(theta)
y <- r * sin(theta)

for (col_name in cj_topicnames1) {
  condition <- sampled_data2_0[[col_name]] > 2 * mean_proportions_f[[col_name]]
  sampled_data2_0$climatejustice[condition] <- 1.0
}

sampled_rows2_0 <- sample(1:nrow(sampled_data2_0), num_points)

ggplot(data = sampled_data2_0[sampled_rows2_0, ], aes(x, y)) +
  geom_point(aes(alpha = climatejustice), size = 3, color = "red") +
  scale_alpha_continuous(range = c(0, 1), guide = "none") +
  theme_void() +
  coord_fixed()

summary(sampled_data2_0[sampled_rows2_0, ]$climatejustice)
# climatejustice mean 0.576

summary(sampled_data2_1[sampled_rows2, ]$climatejustice)
# mean 0.71
# about 23% higher for women last authors
```

```{r random sample blobs full group majority female}
sampled_data3_1 <- data[data$majority_female_binary == "1.0", ]
sampled_data3_1$climatejustice <- 0.0

for (col_name in cj_topicnames1) {
  condition <- sampled_data3_1[[col_name]] > 2 * mean_proportions_f[[col_name]]
  sampled_data3_1$climatejustice[condition] <- 1.0
}

# draw a random sample of 250 rows
set.seed(1726)  
num_points <- 500

# generate random polar coordinates within a circle
theta <- runif(num_points, 0, 2 * pi)
r <- sqrt(runif(num_points))

# convert polar coordinates to Cartesian coordinates
x <- r * cos(theta)
y <- r * sin(theta)

sampled_rows3 <- sample(1:nrow(sampled_data3_1), num_points)

ggplot(data = sampled_data3_1[sampled_rows3, ], aes(x, y)) +
  geom_point(aes(alpha = climatejustice), size = 3, color = "red") +
  scale_alpha_continuous(range = c(0, 1), guide = "none") +
  theme_void() +
  coord_fixed()

```

```{r random sample blobs full group majority male}
sampled_data3_0 <- data[data$majority_female_binary == "0.0", ]
sampled_data3_0$climatejustice <- 0.0

# draw a random sample of 250 rows
set.seed(1727)  
num_points <- 500

# generate random polar coordinates within a circle
theta <- runif(num_points, 0, 2 * pi)
r <- sqrt(runif(num_points))

# convert polar coordinates to Cartesian coordinates
x <- r * cos(theta)
y <- r * sin(theta)

for (col_name in cj_topicnames1) {
  condition <- sampled_data3_0[[col_name]] > 2 * mean_proportions_f[[col_name]]
  sampled_data3_0$climatejustice[condition] <- 1.0
}

sampled_rows3_0 <- sample(1:nrow(sampled_data3_0), num_points)

ggplot(data = sampled_data3_0[sampled_rows3_0, ], aes(x, y)) +
  geom_point(aes(alpha = climatejustice), size = 3, color = "red") +
  scale_alpha_continuous(range = c(0, 1), guide = "none") +
  theme_void() +
  coord_fixed()

summary(sampled_data3_0[sampled_rows3_0, ]$climatejustice)
# climatejustice mean 0.624

summary(sampled_data3_1[sampled_rows3, ]$climatejustice)
# mean 0.768
# about 23% higher for women-dominated full author groups
```

