---
title: "stm.R"
author: "D. Danilenko"
date: "2023-08-16"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load necessary libraries}
# load all the necessary libraries
library("stm")
library("quanteda")
library("stminsights")
library("tidyverse")
library("readxl")
library("dplyr")
library("ggplot2")
library("tidytext")
library("gutenbergr")
library("reshape2")
library("gridExtra")
library("forestplot")
library("wesanderson")
library("tidyr")
library("betareg")
library("hrbrthemes")
library("plotly")
library("viridis")
library("heatmaply")
library("countrycode")
library("margins")
library("marginaleffects")
```

```{r load the dataset}
# load the dataset
# rm(data)
data <- read.csv('data/data_complete.csv', header = TRUE)
data <- data %>%
  select(c("id", "abstract","title","keywords",
           "majority_female_binary","first_author_female","last_author_female","subfield","impact","X1_gii_quartile", "X2_gii_quartile", "year"))

data$text <- "text"

# prepare the variables for stm
data <- data %>%
  mutate(impact = if_else(is.na(impact) | impact == "None", "unknown", impact))
data$subfield <- as.factor(data$subfield)
data$first_author_female <- as.factor(data$first_author_female)
data$last_author_female <- as.factor(data$last_author_female)
data$majority_female_binary <- as.factor(data$majority_female_binary)
data$impact <- as.factor(data$impact)
data$X1_gii_quartile <- as.factor(data$X1_gii_quartile)
data$X2_gii_quartile <- as.factor(data$X2_gii_quartile)
```

```{r process the data, create tokens}
### DATA PROCESSING ###
# building a corpus using quanteda
# combine title, abstract and keywords in a column called text
data$text <- paste(data$title, data$abstract, data$keywords)

# get rid of the copyright information in our corpus
data <- data %>% separate(text, c("text","copyright"), sep = "\\(c\\)\\s*\\d+", extra="merge", remove = TRUE) #removes (c) followed by numbers - this covers most copyright messages
data$text <- gsub("all rights reserved"," ",as.character(data$text))

# create the actual CORPUS 
corp <- corpus(data, text_field = "text")
summary(corp, 3)

# the function automatically assumes all other columns contain document variables
head(docvars(corp)) 

# create TOKENS from this - this basically just means cutting up the text into individual words
toks <- tokens(corp)
#the below is a fairly standard list for pre-processing
toks <- tokens(corp, remove_punct = TRUE, remove_symbols = TRUE) %>% #create tokens w/o punctuation or symbols
  tokens_tolower() %>% #lowercase -- note the pipe means this function doesn't need any input
  tokens_remove(pattern = stopwords("en"), #remove stopwords
                min_nchar = 2) %>% #remove short words. AMR is three letters, so best keep it to 2
  tokens_wordstem(language = "en") #Using snowball stemmer

# create two dfms: one with unigrams and one with bi-grams
dfm_single = dfm(toks)%>%
  dfm_trim(min_termfreq = 100, termfreq_type = "count", max_docfreq=0.95, docfreq_type = "prop")

toks_bigram <- tokens_ngrams(toks, n = 2, skip = 1:2)
dfm_bigram <- dfm(toks_bigram) %>%
  dfm_trim(min_termfreq = 100, termfreq_type = "count", max_docfreq=0.95, docfreq_type = "prop")

# combine
dfm = cbind(dfm_bigram, dfm_single)

# show most-frequent tokens:
topfeatures(dfm, 15) # should include some bi-grams now
```

```{r quanteda metadata conversion}
#STM can take Quanteda dfms directly, so there is usually no reason to convert
#However, sometimes STM gets confused about data types etc. If you want to convert, use the below
#Note that in the stm call, you then need to manually input the docs, vocab and meta data
#Also the docvars bit is absolutely essential for STM's co-variance to work!
dfm_stm <- quanteda::convert(dfm, to = c("stm"),docvars=docvars(dfm))
dfm_stm$meta$year <- as.numeric(dfm_stm$meta$year)
dfm_stm$meta$first_author_female <- as.factor(dfm_stm$meta$first_author_female)
dfm_stm$meta$last_author_female <- as.factor(dfm_stm$meta$last_author_female)
dfm_stm$meta$majority_female_binary <- as.factor(dfm_stm$meta$majority_female_binary)
docs <- dfm_stm$documents
vocab <- dfm_stm$vocab
meta <- dfm_stm$meta
```

```{r load the topic model}
model120_1 <- readRDS(file = "data/240823_120_1.Rds")
```

```{r define justice topics}
# define CJ topics through manual exploration

cj_topics <- c(12,21,25,37,44,50,56,80,83,91,101,118,119) 
cj_topicnames <- c("Resilience","Food Security","Vulnerability","Adaptive Capacity","Governance","Local Knowledge","Island Territories","Climate Finance","Rural Households","Transformation Discourse","Community","Social Capital","Migration")
cj_topicnames1 <- c("resilience","food_security","vulnerability","adaptive_capacity","governance","local_knowledge","island_territories","climate_finance","rural_households","transformation_discourse","community","social_capital","migration")

```

```{r estimate metadata effects}
set.seed(2911)

# try fewer degrees of freedom for the spline, try taking out the spline
prep1 <-  estimateEffect(~first_author_female + #s(year)
                           #subfield +
                           X1_gii_quartile + 
                         impact, 
                          # subfield*first_author_female +
                           #impact*first_author_female +
                           #X1_gii_quartile*first_author_female,
                         model120_1,
                         metadata = meta)

# try to change the encoding of data for the gender variable
# so we want to get a separate estimate for 0.0, 1.0, and unknown

prep2 <- estimateEffect(~last_author_female +
                           #s(year) + subfield + 
                           X2_gii_quartile + impact,  
                           #subfield*last_author_female +
                           #impact*last_author_female +
                           #X2_gii_quartile*last_author_female, 
                         model120_1,
                         metadata = meta)


prep3 <- estimateEffect (~majority_female_binary +
                           #s(year) + subfield + 
                            X2_gii_quartile + impact,
                           #subfield*majority_female_binary +
                           #impact*majority_female_binary +
                           #X2_gii_quartile*majority_female_binary, 
                          model120_1,
                         metadata = meta)
```

```{r stm_insights}
# STM insights web version
out <- quanteda::convert(dfm, to = "stm",docvars=docvars(dfm))
save.image("291123_stm.RData") #This has to contain prep,
#Uncomment & run to launch the app
run_stminsights()
```

```{r extract mean topic score}
# extract mean topic prevalence

proportions_table <- make.dt(model120_1)
mean_proportions <- as.data.frame(summarize_all(proportions_table, mean))
mean_proportions <- subset(mean_proportions, select = -docnum)
new_col_names <- as.character(1:120)
colnames(mean_proportions) <- new_col_names

# make graphs with the relative change instead of absolute

mean_proportions_f <- mean_proportions %>%
  select(all_of(cj_topics))

transformed_df <- mean_proportions %>%
  pivot_longer(everything(), names_to = "topic", values_to = "mean_proportion")

transformed_df_f <- transformed_df %>%
  filter(topic %in% cj_topics)
```

```{r extract effect as difference}
### EXTRACT AND EXPLORE EFFECTS ### 
### GENDER ###

effects1 <- get_effects(estimates = prep1,
                       variable = 'first_author_female',
                       type = 'difference',
                       cov_val1="1.0",cov_val2="0.0")

effects2 <- get_effects(estimates = prep2,
                        variable = 'last_author_female',
                        type = 'difference',
                        cov_val1="1.0",cov_val2="0.0")

effects3 <- get_effects(estimates = prep3,
                        variable = 'majority_female_binary',
                        type = 'difference',
                        cov_val1="1.0",cov_val2="0.0")
```

```{r filtered and relative effects}
### TIDY UP THE RESULTS AND MAKE GRAPHS ###
# forest plots gender x control x topic (topics ordered by prevalence)

# match the full dataset to topic names - exclude irrelevant

# add topic names for all included topics
# add mean proportions for all included topics if we want to see relative difference
# filter to climate justice topics
effects1_f <- effects1 %>%
  filter(topic %in% topic_names$topic)
effects1_f <- merge(effects1_f, transformed_df, by = "topic")
effects1_f$relativedifference <- effects1_f$difference/effects1_f$mean_proportion
effects1_f$relativelower <- effects1_f$lower/effects1_f$mean_proportion
effects1_f$relativeupper <- effects1_f$upper/effects1_f$mean_proportion
effects1_f <- merge(effects1_f, topic_names[c("topic", "topicname")], by="topic",all.x=TRUE)

effects2_f <- effects2 %>% 
  filter(topic %in% topic_names$topic)
effects2_f <- merge(effects2_f, transformed_df, by = "topic")
effects2_f$relativedifference <- effects2_f$difference/effects2_f$mean_proportion
effects2_f$relativelower <- effects2_f$lower/effects2_f$mean_proportion
effects2_f$relativeupper <- effects2_f$upper/effects2_f$mean_proportion
effects2_f <- merge(effects2_f, topic_names[c("topic", "topicname")], by="topic",all.x=TRUE)

effects3_f <- effects3 %>%
  filter(topic %in% topic_names$topic)
effects3_f <- merge(effects3_f, transformed_df, by = "topic")
effects3_f$relativedifference <- effects3_f$difference/effects3_f$mean_proportion
effects3_f$relativelower <- effects3_f$lower/effects3_f$mean_proportion
effects3_f$relativeupper <- effects3_f$upper/effects3_f$mean_proportion
effects3_f <- merge(effects3_f, topic_names[c("topic", "topicname")], by="topic",all.x=TRUE)
```

```{r forest plot 1st author}
### VISUALISATION ###
### FOREST PLOTS ###
# save graphs in width = 800

# these values do not match the ones i have in other graphs - check
# no these effects are actually different in number and sign - why ? 
# i used exactly the same data and the same process 

# first sanity check would be to run now the same thing just for the CJ topics and compare the numbers again 
label_function <- function(value, alpha_value) {
  if (alpha_value == 1.0) {
    return(bquote(bold(.(value))))
  } else {
    return(as.character(value))
  }
}
# colour all of the variables similarly - if below 0 - colour green, if above 0 colour orange
alpha_value <- ifelse(effects1_f$topicname %in% cj_topicnames, 1, 0.5)

### FIRST AUTHOR DIFFERENCE ###
subt <- c("← First author predicted male            First author predicted female →")
fp1 <- ggplot(data=effects1_f, aes(x=topicname, y=relativedifference, ymin=relativelower, ymax=relativeupper)) +
  labs(title = "Mean effect of first author gender",
       subtitle = "Relative difference in topic proportion") +
  geom_pointrange(colour = wes_palette("Darjeeling1")[5], shape=18, size = 0.25, alpha=alpha_value) + 
  geom_hline(yintercept=0, lty=2, colour ='darkgrey') +  # add a dotted line at x=1 after flip
  coord_flip() +  # flip coordinates (puts labels on y axis)
  scale_y_continuous(limits = c(-1, 1))  +
  scale_x_discrete(expand = c(0.01, 0.01)) + 
  xlab('') + 
  ylab(subt) +
  theme(
        plot.title = element_text(hjust = 0.5, size = 14),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text.y = element_text(size = 7.5))


fp1 <- fp1 +
  scale_y_continuous(
    limits = c(-1, 1),
    labels = function(x) label_function(x, alpha_value)
  ) +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14),
    plot.subtitle = element_text(hjust = 0.5),
    axis.text.y = element_text(size = 7.5)
  )
print(fp1)
ggsave("graphs/1_gender_all.png", fp1, width = 6.9, height = 9.9, dpi = 1000)
```
```{r forest plot last author}
### LAST AUTHOR DIFFERENCE ###
# alpha = 1 for cj_topics and alpha = 0.5 for the rest
alpha_value <- ifelse(effects2_f$topicname %in% cj_topicnames, 1, 0.25)

fp2 <- ggplot(data=effects2_f, aes(x=topicname, y=relativedifference, ymin=relativelower, ymax=relativeupper)) +
  labs(title = "Mean effect of last author gender",
       subtitle = "Relative difference in topic proportion") +
  geom_pointrange(colour = wes_palette("Darjeeling1")[1], shape=18, size = 0.25, alpha = alpha_value) + 
  geom_hline(yintercept=0, lty=2, colour ='darkgrey') +  # add a dotted line at x=1 after flip
  coord_flip() +  # flip coordinates (puts labels on y axis)
  scale_y_continuous(limits = c(-1, 1))  +
  scale_x_discrete(expand = c(0.01, 0.01)) +
  xlab('') + 
  ylab(subt2) +
  theme(
        plot.title = element_text(hjust = 0.5, size = 14),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text.y = element_text(size = 7.5, face = ifelse(alpha_value == 1, "bold", "plain")))
print(fp2)

# for some reason the bold highlight is messing up - check later
ggsave("graphs/2_gender_all.png", fp2, width = 6.9, height = 9.9, dpi = 1000)
```

```{r forest plot full group}
### MAJORITY AUTHOR DIFFERENCE ###
alpha_value <- ifelse(effects3_f$topicname %in% cj_topicnames, 1, 0.5)
face_value <- ifelse(alpha_value == 1, "bold", "plain")
subt3 <- c("← Majority author predicted male            Majority author predicted female →")
fp3 <- ggplot(data=effects3_f, aes(x=topicname, y=relativedifference, ymin=relativelower, ymax=relativeupper)) +
  labs(title = "Mean effect of majority author gender",
       subtitle = "Relative difference in topic proportion") +
  geom_pointrange(colour = wes_palette("Darjeeling1")[3], shape=18, size = 0.25, alpha=alpha_value) + 
  geom_hline(yintercept=0, lty=2, colour ='darkgrey') +
  coord_flip() +
  scale_y_continuous(limits = c(-1, 1))  +
  scale_x_discrete(expand = c(0.01, 0.01)) +
  xlab('') + 
  ylab(subt3) +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14),
    plot.subtitle = element_text(hjust = 0.5),
    axis.text.y = element_text(size = 7.5, face = ifelse(alpha_value == 1, "bold", "plain"))
  )
print(fp3)
ggsave("graphs/3_gender_all.png", fp3, width = 6.9, height = 9.9, dpi = 1000)
```

```{r beta regression aggregate}
b_reg <- betareg(climatejusticescore ~first_author_female + year + broader_subfield +
                      X1_gii + impact_factor + 
                      broader_subfield*first_author_female +     
                      impact_factor*first_author_female +
                      X1_gii*first_author_female, data = data1)
summary(b_reg)
```

```{r beta regression aggregate: predict}



```


